-- Migration: change_flashcard_source_column
-- Description: Changes is_generated_by_ai boolean to source ENUM('manual', 'ai')
-- Author: GitHub Copilot
-- Date: 2025-04-21

-- Create the source type enum
do $$ begin
    create type flashcard_source as enum ('manual', 'ai');
exception
    when duplicate_object then null;
end $$;

-- Add the new column
alter table flashcard 
    add column if not exists source flashcard_source;

-- Migrate existing data
update flashcard
set source = case 
    when is_generated_by_ai = true then 'ai'::flashcard_source
    else 'manual'::flashcard_source
end;

-- Make the new column required
alter table flashcard 
    alter column source set not null;

-- Drop the old column
alter table flashcard 
    drop column if exists is_generated_by_ai;

-- Add a check constraint to ensure source is either 'manual' or 'ai'
alter table flashcard
    add constraint check_valid_source 
    check (source in ('manual', 'ai'));

-- Update the RLS policies to use the new column
drop policy if exists "Users can view their own flashcards" on flashcard;
drop policy if exists "Users can create their own flashcards" on flashcard;
drop policy if exists "Users can update their own flashcards" on flashcard;
drop policy if exists "Users can delete their own flashcards" on flashcard;

-- Recreate the policies with the new column
create policy "Users can view their own flashcards"
    on flashcard
    for select
    to authenticated
    using (auth.uid() = user_id);

create policy "Users can create their own flashcards"
    on flashcard
    for insert
    to authenticated
    with check (auth.uid() = user_id);

create policy "Users can update their own flashcards"
    on flashcard
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

create policy "Users can delete their own flashcards"
    on flashcard
    for delete
    to authenticated
    using (auth.uid() = user_id);

comment on column flashcard.source is 'Indicates whether the flashcard was created manually or generated by AI. Can be either ''manual'' or ''ai''.';